export const orders = [
  {
    id: "ORD-1001",
    customer: "Amit Sharma",
    email: "amit@example.com",
    amount: 2499,
    status: "Paid",
    method: "UPI",
    items: 3,
    city: "Delhi",
    date: "2026-06-10",
  },
  {
    id: "ORD-1002",
    customer: "Neha Verma",
    email: "neha@example.com",
    amount: 1299,
    status: "Paid",
    method: "Card",
    items: 1,
    city: "Mumbai",
    date: "2026-06-09",
  },
  {
    id: "ORD-1003",
    customer: "Rahul Mehta",
    email: "rahul@example.com",
    amount: 3999,
    status: "Failed",
    method: "NetBanking",
    items: 5,
    city: "Bangalore",
    date: "2026-06-08",
  },
  {
    id: "ORD-1004",
    customer: "Sara Khan",
    email: "sara@example.com",
    amount: 799,
    status: "Paid",
    method: "UPI",
    items: 2,
    city: "Lucknow",
    date: "2026-06-07",
  },
  {
    id: "ORD-1005",
    customer: "Vikram Singh",
    email: "vikram@example.com",
    amount: 1599,
    status: "Refunded",
    method: "Card",
    items: 1,
    city: "Pune",
    date: "2026-06-06",
  },
];

export const products = [
  {
    id: 1,
    name: "MacBook Pro",
    price: 1999,
    stock: 12,
    status: "In Stock",
  },
  {
    id: 2,
    name: "iPhone 15",
    price: 999,
    stock: 0,
    status: "Out of Stock",
  },
];